import { Data } from "../../types/axios.type";

export const datas: Data[] = [
  {
    id: 1,
    title: "iPhone 9",
    description: " An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: undefined,
    images: [],
  },
  {
    id: 2,
    title: "iPhone 9",
    description: " An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: undefined,
    images: [],
  },
  {
    id: 3,
    title: "iPhone 9",
    description: " An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: undefined,
    images: [],
  },
  {
    id: 4,
    title: "iPhone 9",
    description: " An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: undefined,
    images: [],
  },
];
